spring:
  batch:
    job:
      names: ${job.name:NONE}
  jpa:
    show-sql: false
    hibernate:
      format_sql: true
      ddl-auto: none

databases:
  mysql:
    properties:
      "[hibernate.show_sql]": true
      "[hibernate.hbm2ddl.auto]": none
      "[hibernate.default_batch_fetch_size]": ${chunkSize:100}
      "[hibernate.dialect]": org.hibernate.dialect.MySQL57Dialect
      "[hibernate.physical_naming_strategy]": org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#      hibernate.show_sql: false
#      hibernate.hbm2ddl.auto: none
#      hibernate.default_batch_fetch_size: ${chunkSize:100}
#      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/spring_batch
        username: spring
        password: Springtest2021!
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximumPoolSize: 10
  postgre:
    properties:
      "[hibernate.show_sql]": false
      "[hibernate.hbm2ddl.auto]": none
      "[hibernate.default_batch_fetch_size]": ${chunkSize:100}
      "[hibernate.default_schema]": spring
    datasource:
      hikari:
        jdbc-url: jdbc:postgresql://localhost:5432/spring
        username: test
        password: test!
        driver-class-name: org.postgresql.Driver
        maximum-pool-size: 10 # pool에 유지할 최대 connection 수
  mysql-practice:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/practice
        username: spring
        password: Springtest2021!
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximumPoolSize: 10
mybatis:
  mapper-locations: classpath*:**/mapper/*.xml

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectionTimeout: 15000
        readTimeout: 15000
        loggerLevel: FULL

logging:
  level:
    org:
      springframework: info