spring:
  datasource:
  #    url: jdbc:postgresql://localhost:5432/spring
  #    username: test
  #    password: test!
  #    driver-class-name: org.postgresql.Driver
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
  #    username: sa
  #    password:
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  cloud:
    config:
      name: test
      profile: native
  config:
    import: optional:configserver:http://localhost:8888

