spring:
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  cloud:
    config:
      name: test
      profile: native
  config:
    import: optional:configserver:http://localhost:8888

