spring:
  profiles:
    active: local

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch
    username: spring
    password: Springtest2021!
  batch:
    job:
#      enabled: false #어플리케이션 구동시 컨텍스트 내의 모든 스프링 배치 작업 자동 실행 여부
      names: ${job.name:EMPTY} # argument로 전달하는 job 수행
#    jdbc:
#      initialize-schema: always # 스프링 부트가 스프링 배치 스키마 스크립트를 실행하도록 지시
  config:
    activate:
      on-profile: local
#logging:
#  level:
#    org:
#      springframework:
